### ISSUE TITLE
Bug: Doesn't seem to work on recent build for Pixel 6 : 15.0.0 (AP4A.241205.013, Dec 2024)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [LSPosed/DisableFlagSecure#77]
### LSPosed version

It says on the app: "1.9.3_mod (7244) - Zygisk"

### Android version

15.0.0 (AP4A.241205.013, Dec 2024)

### Custom OS version

Not a custom OS. It's just a rooted 15.0.0 (AP4A.241205.013, Dec 2024)

### Version requirement

- [X] I am using latest debug CI version

### Behavior

Ever after flashing the latest version of Android into Pixel 6, I can't get any module of unblocking screenshots to work anymore.
I personally use it for mirroring the device using ScrCpy, and it doesn't work well there anymore.
For example I open Authy app, and it doesn't show its content. Just black.

About "latest debug CI version" I don't understand what it means.
Here's a short video of what I have:

[scrcpy_2024-12-12_21-39-05.zip](https://github.com/user-attachments/files/18116670/scrcpy_2024-12-12_21-39-05.zip)

### Logs

I don't understand what logs, from where. I hope it's right, that I use LSPosed UI to get the "verbose logs" you want.

[LSPosed_2024-12-12T21_40_53.645911.zip](https://github.com/user-attachments/files/18116688/LSPosed_2024-12-12T21_40_53.645911.zip)

### Framework, Services, and Screenshot App

Those files are indeed too large to fit into a single ZIP file. Max allowed is 25MB.
Here they are in 2 files instead:

[jars.zip](https://github.com/user-attachments/files/18116486/jars.zip)

[System UI - package com.android.systemui - versionCode 35.apk.zip](https://github.com/user-attachments/files/18116482/System.UI.-.package.com.android.systemui.-.versionCode.35.apk.zip)

**Comment by aviraxp** [comment]
lsposed issue.

**Comment by AndroidDeveloperLB** [comment]
@aviraxp What do you mean? What can I do? Did I do something wrong? Please explain.

**Comment by AndroidDeveloperLB** [comment]
@aviraxp I was told by LSPosed that it's not an issue with it, but with the module.
https://github.com/JingMatrix/LSPosed/issues/139#issuecomment-2560466991

Please talk with them as I've tried to report both the module here and on LSPosed, and you tell me to reach the other...

**Comment by aviraxp** [comment]
Only report if it is reproducible on internal test version of lsposed.

**Comment by AndroidDeveloperLB** [comment]
@aviraxp I have. I did exactly as I was told:
https://github.com/JingMatrix/LSPosed/issues/139#issuecomment-2560439783

Please talk with them.

**Comment by JingMatrix** [comment]
Is this module guaranteed to work with `scrcpy`? I tested it and found that it worked on phone but not with `scrcpy`.
Maybe an issue with `scrpy` updates?

**Comment by AndroidDeveloperLB** [comment]
@JingMatrix It worked fine in the past:
https://github.com/Genymobile/scrcpy/issues/3049#issuecomment-1221538985

**Comment by znbaboy** [comment]
I can confirm that this is an issue with the module itself. The last working version is 3.1.0.

Any version after this, I am not able to view my Google Pay screen while mirroring through a SCRCPY. I am just given a black screen.

**Comment by AndroidDeveloperLB** [comment]
@aviraxp I can confirm. Version 3.1.0 works fine.
It's something that has changed over the past new versions after that, that can't work with recent versions of Android...
Tested on Pixel 6 with Android 15 , build AP4A.250205.002.

**Comment by AndroidDeveloperLB** [comment]
@tehcneko Fixed in general, right? Not just ScrCpy. It also existed for screenshots, Android Studio, ...

**Comment by znbaboy** [comment]
On my A13 device, the 4.2.0 still gives me a black screen when using Google Pay. 

This is not an issue with 3.1.0.

**Comment by aviraxp** [comment]
Update scrcpy to latwst version, so ot uses virtual display by default.

**Comment by aviraxp** [comment]
Update scrcpy to latwst version, so ot uses virtual display by default.

**Comment by znbaboy** [comment]
the issue still persists.

I am connecting from Scrcpy 3.1

https://github.com/user-attachments/assets/a7c90fba-8961-414e-ab45-bbc2e945f750

**Comment by znbaboy** [comment]
so this was 

> the issue still persists.
> 
> I am connecting from Scrcpy 3.1
> 20250310-1853-31.6755188.mp4



> the issue still persists.
> 
> I am connecting from Scrcpy 3.1
> 20250310-1853-31.6755188.mp4

this was happening on Android 13 but seems to work fine on A14+
